### ISSUE TITLE
Lint dirty/modified files only

### ISSUE THREAD

**Issue by thasmo** [webpack-contrib/eslint-loader#304]
# Feature Proposal
Add an option similar to the [`lintDirtyModulesOnly` option of the styleling plugin](https://webpack.js.org/plugins/stylelint-webpack-plugin/#lintdirtymodulesonly), which only lints changed files and skips linting on start; could be `false` by default.

# Use Case
Introducing linting to an existing big project is a lot of work and a possibility to lint and fix only changed files can be a huge benefit, as errors and warnings show up only for those files.

**Comment by DiscoNova** [comment]
I do see a benefit of this... but - to me at least - it appears that this approach could lead to issues somewhere down the road.

Doing tons of changes (that may be completely unrelated to the change you intended to make simply because it was dismissed from linting before) on a file you're modifying for a specific thing ... can easily lead to things getting missed on peer review.

Whereas... if the file fails linting without the changes you've made, that gets fixed first (which is everything literally connected to the thing you want to change) ... and *then* you modify things in another commit ... to me - that would seem like a more clear approach.

**Comment by ricardogobbosouza** [comment]
@thasmo this would require creating a plugin, which runs a little farther, as this is a loader.
We can think of creating an `eslint-webpack-plugin` plugin that incorporates this loader, what do you think @evilebottnawi ?

**Comment by evilebottnawi** [comment]
@ricardogobbosouza yes, it is require create plugin, plugins also have more api than loader, maybe it is good idea migrate on plugin

**Comment by ricardogobbosouza** [comment]
@evilebottnawi Should we create a separate repository? or migrate this one?

**Comment by evilebottnawi** [comment]
@ricardogobbosouza will be great create separate repo and deprecate this after official release. Do you want to do it? If yes, just ping me again and i will create new repo

**Comment by evilebottnawi** [comment]
@ricardogobbosouza Welcome https://github.com/webpack-contrib/eslint-webpack-plugin :tada:

**Comment by ricardogobbosouza** [comment]
@evilebottnawi thanks

**Comment by ricardogobbosouza** [comment]
@evilebottnawi it's almost ready
https://github.com/webpack-contrib/eslint-webpack-plugin/ :smile: 

Can configure azure pipeline?
https://github.com/webpack-contrib/eslint-webpack-plugin/issues/1

**Comment by thasmo** [comment]
@ricardogobbosouza, awesome - didn't expect to have this so fast. Very nice! Going to look into it asap. 👍

**Comment by ricardogobbosouza** [comment]
@thasmo thanks

See https://github.com/webpack-contrib/eslint-webpack-plugin#lintdirtymodulesonly

**Comment by ricardogobbosouza** [comment]
I'll leave it open for now, but the idea is to use `eslint-webpack-plugin`.
